/**
 * Catalog rows for `prisma/seed.ts` — keep keys stable (unlock rows reference keys).
 * `category` drives modal filter chips and grouping.
 */
export type AchievementCatalogSeedRow = {
  id: string;
  key: string;
  name: string;
  description: string;
  icon: string;
  titleReward: string | null;
  category: string;
  sortOrder: number;
};

export const ACHIEVEMENT_CATALOG_SEED: AchievementCatalogSeedRow[] = [
  // --- Combat intro & guild raid (legacy / meta) ---
  {
    id: "ach_first_blood",
    key: "first_blood",
    name: "First Blood",
    description: "Win your first solo fight.",
    icon: "⚔️",
    titleReward: "Firstblood",
    category: "combat_style",
    sortOrder: 0,
  },
  {
    id: "ach_survivor",
    key: "survivor",
    name: "Survivor",
    description: "Win a solo fight at or below 20% HP.",
    icon: "🛡️",
    titleReward: "Survivor",
    category: "combat_style",
    sortOrder: 1,
  },
  {
    id: "ach_ratbane",
    key: "ratbane",
    name: "Ratbane",
    description: "Defeat the Sewer Rat King with your guild.",
    icon: "👑",
    titleReward: "Ratbane",
    category: "guild_social",
    sortOrder: 2,
  },
  {
    id: "ach_armed",
    key: "armed",
    name: "Armed",
    description: "Equip a weapon.",
    icon: "🗡️",
    titleReward: null,
    category: "gear",
    sortOrder: 3,
  },
  {
    id: "ach_prepared",
    key: "prepared",
    name: "Prepared",
    description: "Drink a crimson tonic (in or out of combat).",
    icon: "🧪",
    titleReward: null,
    category: "combat_style",
    sortOrder: 4,
  },
  // --- Level milestones ---
  {
    id: "ach_greenhorn",
    key: "greenhorn",
    name: "Greenhorn",
    description: "Reach level 3.",
    icon: "🌱",
    titleReward: null,
    category: "level",
    sortOrder: 10,
  },
  {
    id: "ach_novice_adventurer",
    key: "novice_adventurer",
    name: "Novice Adventurer",
    description: "Reach level 5.",
    icon: "⭐",
    titleReward: "Novice",
    category: "level",
    sortOrder: 11,
  },
  {
    id: "ach_seasoned_adventurer",
    key: "seasoned_adventurer",
    name: "Seasoned Adventurer",
    description: "Reach level 10.",
    icon: "✨",
    titleReward: "Seasoned",
    category: "level",
    sortOrder: 12,
  },
  {
    id: "ach_level_twenty",
    key: "level_twenty",
    name: "Twenty & True",
    description: "Reach level 20.",
    icon: "📐",
    titleReward: null,
    category: "level",
    sortOrder: 13,
  },
  {
    id: "ach_journeyman",
    key: "journeyman",
    name: "Journeyman",
    description: "Reach level 15.",
    icon: "🧭",
    titleReward: null,
    category: "level",
    sortOrder: 14,
  },
  {
    id: "ach_veteran",
    key: "veteran",
    name: "Veteran",
    description: "Reach level 25.",
    icon: "🎖️",
    titleReward: null,
    category: "level",
    sortOrder: 15,
  },
  {
    id: "ach_keystone",
    key: "keystone",
    name: "Keystone",
    description: "Reach level 30.",
    icon: "🏔️",
    titleReward: null,
    category: "level",
    sortOrder: 16,
  },
  {
    id: "ach_luminous",
    key: "luminous",
    name: "Luminous",
    description: "Reach level 40.",
    icon: "🔆",
    titleReward: null,
    category: "level",
    sortOrder: 17,
  },
  {
    id: "ach_colossus",
    key: "colossus",
    name: "Colossus",
    description: "Reach level 45.",
    icon: "🗿",
    titleReward: null,
    category: "level",
    sortOrder: 18,
  },
  {
    id: "ach_paragon",
    key: "paragon",
    name: "Paragon",
    description: "Reach level 50.",
    icon: "💎",
    titleReward: "Paragon",
    category: "level",
    sortOrder: 19,
  },
  // --- Damage / execution (legacy combat stats) ---
  {
    id: "ach_bladebound",
    key: "bladebound",
    name: "Bladebound",
    description: "Deal 1,000 total melee damage (solo or guild raid).",
    icon: "⚔️",
    titleReward: null,
    category: "combat_style",
    sortOrder: 30,
  },
  {
    id: "ach_spellscarred",
    key: "spellscarred",
    name: "Spellscarred",
    description: "Deal 1,000 total magic damage.",
    icon: "🔥",
    titleReward: null,
    category: "combat_style",
    sortOrder: 31,
  },
  {
    id: "ach_deadeye",
    key: "deadeye",
    name: "Deadeye",
    description: "Deal 1,000 total ranged damage.",
    icon: "🏹",
    titleReward: null,
    category: "combat_style",
    sortOrder: 32,
  },
  {
    id: "ach_unbroken",
    key: "unbroken",
    name: "Unbroken",
    description: "Brace 100 times (Defend).",
    icon: "🛡️",
    titleReward: "Unbroken",
    category: "combat_style",
    sortOrder: 33,
  },
  {
    id: "ach_bulwark_ten",
    key: "bulwark_ten",
    name: "Bulwark",
    description: "Brace 10 times (Defend).",
    icon: "🔰",
    titleReward: null,
    category: "combat_style",
    sortOrder: 34,
  },
  {
    id: "ach_executioner",
    key: "executioner",
    name: "Executioner",
    description: "Land 100 killing blows.",
    icon: "☠️",
    titleReward: null,
    category: "combat_style",
    sortOrder: 35,
  },
  {
    id: "ach_thread_needle",
    key: "thread_needle",
    name: "Thread the Needle",
    description: "Win a solo fight at or below 10% HP.",
    icon: "🪡",
    titleReward: null,
    category: "combat_style",
    sortOrder: 36,
  },
  {
    id: "ach_steady_aim",
    key: "steady_aim",
    name: "Steady Aim",
    description: "Win 10 solo fights in a row without defeat.",
    icon: "🎯",
    titleReward: null,
    category: "combat_style",
    sortOrder: 37,
  },
  {
    id: "ach_deathless",
    key: "deathless",
    name: "Deathless",
    description: "Win 25 solo fights in a row without defeat.",
    icon: "👻",
    titleReward: "Deathless",
    category: "combat_style",
    sortOrder: 38,
  },
  {
    id: "ach_tonic_ten",
    key: "tonic_ten",
    name: "Apothecary's Friend",
    description: "Drink 10 crimson tonics (tracked across fights).",
    icon: "🍷",
    titleReward: null,
    category: "combat_style",
    sortOrder: 39,
  },
  {
    id: "ach_tonic_hundred",
    key: "tonic_hundred",
    name: "Crimson Habit",
    description: "Drink 100 crimson tonics (tracked across fights).",
    icon: "🧫",
    titleReward: null,
    category: "combat_style",
    sortOrder: 40,
  },
  // --- Solo win chains ---
  {
    id: "ach_relentless",
    key: "relentless",
    name: "Relentless",
    description: "Win 10 solo fights.",
    icon: "🔥",
    titleReward: null,
    category: "solo_wins",
    sortOrder: 50,
  },
  {
    id: "ach_champion",
    key: "champion",
    name: "Champion",
    description: "Win 50 solo fights.",
    icon: "🏅",
    titleReward: null,
    category: "solo_wins",
    sortOrder: 51,
  },
  {
    id: "ach_solo_century",
    key: "solo_century",
    name: "Century Mark",
    description: "Win 100 solo fights.",
    icon: "💯",
    titleReward: null,
    category: "solo_wins",
    sortOrder: 52,
  },
  {
    id: "ach_solo_quarterk",
    key: "solo_quarterk",
    name: "Quarter-Thousand",
    description: "Win 500 solo fights.",
    icon: "⚡",
    titleReward: null,
    category: "solo_wins",
    sortOrder: 53,
  },
  {
    id: "ach_solo_millennium",
    key: "solo_millennium",
    name: "Millennium Slayer",
    description: "Win 1,000 solo fights.",
    icon: "🌟",
    titleReward: "Millennium Slayer",
    category: "solo_wins",
    sortOrder: 54,
  },
  {
    id: "ach_solo_deca_k",
    key: "solo_deca_k",
    name: "Ten Thousand Cuts",
    description: "Win 10,000 solo fights.",
    icon: "✴️",
    titleReward: "Ten Thousand Cuts",
    category: "solo_wins",
    sortOrder: 55,
  },
  // --- Region kill chains (town_outskirts) ---
  {
    id: "ach_rk_to_10",
    key: "rk_to_10",
    name: "Outskirts Sprout",
    description: "Defeat 10 enemies in Town Outskirts.",
    icon: "🌿",
    titleReward: null,
    category: "region_kills",
    sortOrder: 100,
  },
  {
    id: "ach_rk_to_100",
    key: "rk_to_100",
    name: "Outskirts Hunter",
    description: "Defeat 100 enemies in Town Outskirts.",
    icon: "🐀",
    titleReward: null,
    category: "region_kills",
    sortOrder: 101,
  },
  {
    id: "ach_rk_to_1k",
    key: "rk_to_1k",
    name: "Outskirts Predator",
    description: "Defeat 1,000 enemies in Town Outskirts.",
    icon: "🌫️",
    titleReward: "Outskirts Stalker",
    category: "region_kills",
    sortOrder: 102,
  },
  {
    id: "ach_rk_to_10k",
    key: "rk_to_10k",
    name: "Outskirts Annihilator",
    description: "Defeat 10,000 enemies in Town Outskirts.",
    icon: "💀",
    titleReward: "Outskirts Reaper",
    category: "region_kills",
    sortOrder: 103,
  },
  // --- forest_edge ---
  {
    id: "ach_rk_fe_10",
    key: "rk_fe_10",
    name: "Forest Sprout",
    description: "Defeat 10 enemies in Forest Edge.",
    icon: "🍃",
    titleReward: null,
    category: "region_kills",
    sortOrder: 110,
  },
  {
    id: "ach_rk_fe_100",
    key: "rk_fe_100",
    name: "Forest Hunter",
    description: "Defeat 100 enemies in Forest Edge.",
    icon: "🦊",
    titleReward: null,
    category: "region_kills",
    sortOrder: 111,
  },
  {
    id: "ach_rk_fe_1k",
    key: "rk_fe_1k",
    name: "Forest Predator",
    description: "Defeat 1,000 enemies in Forest Edge.",
    icon: "🌲",
    titleReward: "Forest Stalker",
    category: "region_kills",
    sortOrder: 112,
  },
  {
    id: "ach_rk_fe_10k",
    key: "rk_fe_10k",
    name: "Forest Annihilator",
    description: "Defeat 10,000 enemies in Forest Edge.",
    icon: "🥀",
    titleReward: "Thornreaper",
    category: "region_kills",
    sortOrder: 113,
  },
  // --- ancient_ruins ---
  {
    id: "ach_rk_ar_10",
    key: "rk_ar_10",
    name: "Ruins Sprout",
    description: "Defeat 10 enemies in Ancient Ruins.",
    icon: "🪨",
    titleReward: null,
    category: "region_kills",
    sortOrder: 120,
  },
  {
    id: "ach_rk_ar_100",
    key: "rk_ar_100",
    name: "Ruins Hunter",
    description: "Defeat 100 enemies in Ancient Ruins.",
    icon: "🏺",
    titleReward: null,
    category: "region_kills",
    sortOrder: 121,
  },
  {
    id: "ach_rk_ar_1k",
    key: "rk_ar_1k",
    name: "Ruins Predator",
    description: "Defeat 1,000 enemies in Ancient Ruins.",
    icon: "⚱️",
    titleReward: "Ruinbound",
    category: "region_kills",
    sortOrder: 122,
  },
  {
    id: "ach_rk_ar_10k",
    key: "rk_ar_10k",
    name: "Ruins Annihilator",
    description: "Defeat 10,000 enemies in Ancient Ruins.",
    icon: "💎",
    titleReward: "Relicbreaker",
    category: "region_kills",
    sortOrder: 123,
  },
  // --- murk_catacombs ---
  {
    id: "ach_rk_mc_10",
    key: "rk_mc_10",
    name: "Catacomb Sprout",
    description: "Defeat 10 enemies in Murk Catacombs.",
    icon: "🕯️",
    titleReward: null,
    category: "region_kills",
    sortOrder: 130,
  },
  {
    id: "ach_rk_mc_100",
    key: "rk_mc_100",
    name: "Catacomb Hunter",
    description: "Defeat 100 enemies in Murk Catacombs.",
    icon: "🦇",
    titleReward: null,
    category: "region_kills",
    sortOrder: 131,
  },
  {
    id: "ach_rk_mc_1k",
    key: "rk_mc_1k",
    name: "Catacomb Predator",
    description: "Defeat 1,000 enemies in Murk Catacombs.",
    icon: "⚰️",
    titleReward: "Catacomb Stalker",
    category: "region_kills",
    sortOrder: 132,
  },
  {
    id: "ach_rk_mc_10k",
    key: "rk_mc_10k",
    name: "Catacomb Annihilator",
    description: "Defeat 10,000 enemies in Murk Catacombs.",
    icon: "🖤",
    titleReward: "Catacomb Reaper",
    category: "region_kills",
    sortOrder: 133,
  },
  // --- Gear ---
  {
    id: "ach_discerning_eye",
    key: "discerning_eye",
    name: "Discerning Eye",
    description: "Equip a Rare or better item.",
    icon: "💠",
    titleReward: null,
    category: "gear",
    sortOrder: 200,
  },
  {
    id: "ach_epic_attuned",
    key: "epic_attuned",
    name: "Epic Attunement",
    description: "Equip an Epic or better item.",
    icon: "💜",
    titleReward: null,
    category: "gear",
    sortOrder: 201,
  },
  {
    id: "ach_legend_wrapped",
    key: "legend_wrapped",
    name: "Legend-Wrapped",
    description: "Equip a Legendary or better item.",
    icon: "🟡",
    titleReward: "Legend-Wrapped",
    category: "gear",
    sortOrder: 202,
  },
  {
    id: "ach_godly_touch",
    key: "godly_touch",
    name: "God-Touched",
    description: "Equip a Godly item.",
    icon: "✨",
    titleReward: "God-Touched",
    category: "gear",
    sortOrder: 203,
  },
  {
    id: "ach_full_kit",
    key: "full_kit",
    name: "Full Kit",
    description: "Wear a weapon, helm, chest, gloves, and boots.",
    icon: "🎭",
    titleReward: null,
    category: "gear",
    sortOrder: 204,
  },
  {
    id: "ach_kit_rare_plus",
    key: "kit_rare_plus",
    name: "Rare Battalion",
    description: "Fill weapon, helm, chest, gloves, and boots with Rare+ gear.",
    icon: "🛡️",
    titleReward: null,
    category: "gear",
    sortOrder: 205,
  },
  {
    id: "ach_kit_epic_plus",
    key: "kit_epic_plus",
    name: "Epic Battalion",
    description: "Fill weapon, helm, chest, gloves, and boots with Epic+ gear.",
    icon: "⚔️",
    titleReward: null,
    category: "gear",
    sortOrder: 206,
  },
  // --- Economy ---
  {
    id: "ach_gold_earned_1k",
    key: "gold_earned_1k",
    name: "Purse of Copper",
    description: "Earn 1,000 lifetime gold (combat, sales, chests, events).",
    icon: "🪙",
    titleReward: null,
    category: "economy",
    sortOrder: 300,
  },
  {
    id: "ach_gold_earned_10k",
    key: "gold_earned_10k",
    name: "Growing Hoard",
    description: "Earn 10,000 lifetime gold.",
    icon: "💰",
    titleReward: null,
    category: "economy",
    sortOrder: 301,
  },
  {
    id: "ach_gold_earned_100k",
    key: "gold_earned_100k",
    name: "Serious Fortune",
    description: "Earn 100,000 lifetime gold.",
    icon: "🏆",
    titleReward: null,
    category: "economy",
    sortOrder: 302,
  },
  {
    id: "ach_gold_earned_1m",
    key: "gold_earned_1m",
    name: "Dragon's Ledger",
    description: "Earn 1,000,000 lifetime gold.",
    icon: "🐉",
    titleReward: "Dragon's Ledger",
    category: "economy",
    sortOrder: 303,
  },
  {
    id: "ach_gold_spent_1k",
    key: "gold_spent_1k",
    name: "Open Purse",
    description: "Spend 1,000 total gold at shops.",
    icon: "🧾",
    titleReward: null,
    category: "economy",
    sortOrder: 304,
  },
  {
    id: "ach_gold_spent_10k",
    key: "gold_spent_10k",
    name: "Big Spender",
    description: "Spend 10,000 total gold at shops.",
    icon: "💸",
    titleReward: null,
    category: "economy",
    sortOrder: 305,
  },
  {
    id: "ach_items_sold_10",
    key: "items_sold_10",
    name: "Peddler",
    description: "Sell 10 items at the town shop.",
    icon: "📦",
    titleReward: null,
    category: "economy",
    sortOrder: 306,
  },
  {
    id: "ach_items_sold_100",
    key: "items_sold_100",
    name: "Bulk Vendor",
    description: "Sell 100 items at the town shop.",
    icon: "🏪",
    titleReward: null,
    category: "economy",
    sortOrder: 307,
  },
  // --- Guild / social ---
  {
    id: "ach_guildbound",
    key: "guildbound",
    name: "Guildbound",
    description: "Join a guild.",
    icon: "🏰",
    titleReward: "Guildbound",
    category: "guild_social",
    sortOrder: 400,
  },
  {
    id: "ach_guild_founded",
    key: "guild_founded",
    name: "Charter Signed",
    description: "Create a guild.",
    icon: "📜",
    titleReward: null,
    category: "guild_social",
    sortOrder: 401,
  },
  {
    id: "ach_guild_officer",
    key: "guild_officer",
    name: "Officer's Sash",
    description: "Become a guild officer (not owner).",
    icon: "⚔️",
    titleReward: null,
    category: "guild_social",
    sortOrder: 402,
  },
  {
    id: "ach_oathbearer",
    key: "oathbearer",
    name: "Oathbearer",
    description: "Become a guild leader or officer.",
    icon: "⚜️",
    titleReward: "Oathbearer",
    category: "guild_social",
    sortOrder: 403,
  },
  {
    id: "ach_guild_donor_1k",
    key: "guild_donor_1k",
    name: "Guild Supporter",
    description: "Donate 1,000 total gold to guilds.",
    icon: "🤝",
    titleReward: null,
    category: "guild_social",
    sortOrder: 404,
  },
  {
    id: "ach_benefactor",
    key: "benefactor",
    name: "Benefactor",
    description: "Donate 10,000 total gold to guilds.",
    icon: "💎",
    titleReward: "Benefactor",
    category: "guild_social",
    sortOrder: 405,
  },
  {
    id: "ach_treasury_hand",
    key: "treasury_hand",
    name: "Treasury Hand",
    description: "Deposit 5 item stacks into a guild treasury.",
    icon: "📥",
    titleReward: null,
    category: "guild_social",
    sortOrder: 406,
  },
  {
    id: "ach_treasurekeeper",
    key: "treasurekeeper",
    name: "Treasurekeeper",
    description: "Deposit 10 item stacks into a guild treasury.",
    icon: "📦",
    titleReward: "Treasurekeeper",
    category: "guild_social",
    sortOrder: 407,
  },
  {
    id: "ach_treasury_centurion",
    key: "treasury_centurion",
    name: "Vault Centurion",
    description: "Deposit 100 items into guild treasuries (stack quantities count).",
    icon: "🏛️",
    titleReward: null,
    category: "guild_social",
    sortOrder: 408,
  },
  {
    id: "ach_bossbreaker",
    key: "bossbreaker",
    name: "Bossbreaker",
    description: "Deal 10,000 total damage to guild raid bosses.",
    icon: "💥",
    titleReward: "Bossbreaker",
    category: "guild_social",
    sortOrder: 409,
  },
  {
    id: "ach_boss_annihilator",
    key: "boss_annihilator",
    name: "Raid Annihilator",
    description: "Deal 100,000 total damage to guild raid bosses.",
    icon: "☄️",
    titleReward: null,
    category: "guild_social",
    sortOrder: 410,
  },
  // --- Daily login ---
  {
    id: "ach_returning_soul",
    key: "returning_soul",
    name: "Returning Soul",
    description: "Claim 3 daily login chests.",
    icon: "🌅",
    titleReward: null,
    category: "daily",
    sortOrder: 500,
  },
  {
    id: "ach_oathkeeper",
    key: "oathkeeper",
    name: "Oathkeeper",
    description: "Claim 7 daily login chests.",
    icon: "📜",
    titleReward: "Oathkeeper",
    category: "daily",
    sortOrder: 501,
  },
  {
    id: "ach_daily_thirty",
    key: "daily_thirty",
    name: "Month of Dawn",
    description: "Claim 30 daily login chests.",
    icon: "🌄",
    titleReward: null,
    category: "daily",
    sortOrder: 502,
  },
  {
    id: "ach_daily_hundred",
    key: "daily_hundred",
    name: "Hundred Dawns",
    description: "Claim 100 daily login chests.",
    icon: "🌞",
    titleReward: null,
    category: "daily",
    sortOrder: 503,
  },
  {
    id: "ach_daily_gold_tier",
    key: "daily_gold_tier",
    name: "Gilded Sunrise",
    description: "Claim a Gold daily login chest.",
    icon: "🥇",
    titleReward: null,
    category: "daily",
    sortOrder: 504,
  },
  {
    id: "ach_daily_diamond_tier",
    key: "daily_diamond_tier",
    name: "Diamond Sunrise",
    description: "Claim a Diamond daily login chest.",
    icon: "💠",
    titleReward: null,
    category: "daily",
    sortOrder: 505,
  },
  {
    id: "ach_mythic_blessed",
    key: "mythic_blessed",
    name: "Mythic-Blessed",
    description: "Claim a Mythic daily chest.",
    icon: "✨",
    titleReward: "Mythic-Blessed",
    category: "daily",
    sortOrder: 506,
  },
  // --- Exploration ---
  {
    id: "ach_forest_walker",
    key: "forest_walker",
    name: "Forest Walker",
    description: "Travel to Forest Edge.",
    icon: "🌲",
    titleReward: null,
    category: "exploration",
    sortOrder: 600,
  },
  {
    id: "ach_ruin_seeker",
    key: "ruin_seeker",
    name: "Ruin Seeker",
    description: "Travel to Ancient Ruins.",
    icon: "🏛️",
    titleReward: null,
    category: "exploration",
    sortOrder: 601,
  },
  {
    id: "ach_catacomb_delver",
    key: "catacomb_delver",
    name: "Catacomb Delver",
    description: "Travel to Murk Catacombs.",
    icon: "🦇",
    titleReward: null,
    category: "exploration",
    sortOrder: 602,
  },
  {
    id: "ach_scout",
    key: "scout",
    name: "Scout",
    description: "Visit three different wild regions (excluding town).",
    icon: "🧭",
    titleReward: null,
    category: "exploration",
    sortOrder: 603,
  },
  // --- Meta ---
  {
    id: "ach_duskforged",
    key: "duskforged",
    name: "Duskforged",
    description: "Unlock 45 achievements.",
    icon: "🌑",
    titleReward: "Duskforged",
    category: "meta",
    sortOrder: 900,
  },
  {
    id: "ach_founder",
    key: "founder",
    name: "Founder",
    description: "Early tester honorific.",
    icon: "🌟",
    titleReward: "Founder",
    category: "meta",
    sortOrder: 901,
  },
];
