-- AlterEnum
ALTER TYPE "Rarity" ADD VALUE 'GODLY';

-- AlterTable
ALTER TABLE "CharacterEquipment" ADD COLUMN     "affixPrefix" TEXT,
ADD COLUMN     "bonusConstitution" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusCritChance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusDexterity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusIntelligence" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusLifeSteal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusSkillPower" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusStrength" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "InventoryItem" ADD COLUMN     "affixPrefix" TEXT,
ADD COLUMN     "bonusConstitution" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusCritChance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusDexterity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusIntelligence" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonusLifeSteal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusSkillPower" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusStrength" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SoloCombatEncounter" ADD COLUMN     "playerLifeSteal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "playerSkillPowerBonus" DOUBLE PRECISION NOT NULL DEFAULT 0;
